### ISSUE TITLE
Trao đổi về Git

### ISSUE THREAD

**Issue by truongduchuy910** [phamquynhnhumm/Do_An_CN_Phan_Mem#1]
Hiiiiiiiii
Mọi người nắm cơ bản về Git chưa nhỉ? 

- Clone một respository về.
- Commit và đẩy thay đổi lên.

**Comment by truongduchuy910** [comment]
Thảo luận trực tiếp trong này luôn nha, Issue bên Git này cũng giống như comment Facebook thôi.

Hông có câu hỏi hay bàn bạc gì thì comment done để mình đóng Issue nha!

**Comment by phamquynhnhumm** [comment]
done
